#!/bin/bash
#  ██                                            
# ░██              ██████                        
# ░██       ██████░██░░░██ ███     ██ ██████████ 
# ░██████  ██░░░░ ░██  ░██░░██  █ ░██░░██░░██░░██
# ░██░░░██░░█████ ░██████  ░██ ███░██ ░██ ░██ ░██
# ░██  ░██ ░░░░░██░██░░░   ░████░████ ░██ ░██ ░██
# ░██████  ██████ ░██      ███░ ░░░██ ███ ░██ ░██
# ░░░░░   ░░░░░░  ░░      ░░░    ░░░ ░░░  ░░  ░░ 


#---Autostart---#
feh --bg-scale ~/.config/wallpaper.png
~/.config/polybar/launch.sh
~/.config/bspwm/script.sh
sxhkd &

#---BSPWM---#
bspc monitor -d 一 二 三 四 五 六 七 八 九

bspc config border_radius 10

bspc config border_width         5
bspc config window_gap           10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false

#---Colours---#
. "${HOME}/.cache/wal/colors.sh"
bspc config focused_border_color "$color13"
bspc config presel_feedback_color "$color4"

#---Rules---#
bspc config external_rules_command ~/.config/bspwm/external_rules
bspc rule -a Steam desktop=八
bspc rule -a discord desktop=九
bspc rule -a Zathura state=tiled
bspc rule -a firefox:Toolkit state=floating sticky=on
